export type MinimalUserProfile = {
  username?: string | null;
  email?: string | null;
};

/**
 * The backend currently generates a numeric username on first login.
 * Product requirement: do NOT show that numeric username as the "name".
 */
export function isAutoGeneratedNumericUsername(username: string | null | undefined): boolean {
  if (!username) return false;
  const u = username.trim();
  if (!u) return false;
  // Backend uses generateNumericUsername(10)
  return /^\d{10}$/.test(u);
}

/**
 * Name shown in UI:
 * - If user filled a real username -> username
 * - Otherwise -> email
 */
export function getPreferredDisplayName(profile: MinimalUserProfile | null | undefined): string | null {
  const username = profile?.username?.trim() ?? "";
  const email = profile?.email?.trim() ?? "";
  if (username && !isAutoGeneratedNumericUsername(username)) return username;
  if (email) return email;
  return null;
}

/**
 * Username shown in profile fields:
 * - Hide auto-generated numeric username (treat as empty)
 */
export function getUsernameForDisplay(profile: MinimalUserProfile | null | undefined): string | null {
  const username = profile?.username?.trim() ?? "";
  if (!username) return null;
  if (isAutoGeneratedNumericUsername(username)) return null;
  return username;
}

export function getUsernameForEdit(profile: MinimalUserProfile | null | undefined): string {
  return getUsernameForDisplay(profile) ?? "";
}


